## 12 - 03 - 2026  Logistic Regression

In [28]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt  # Matplotlib plotting interface
import seaborn as sns
from sklearn.metrics import confusion_matrix

In [38]:
actual = [0,0,0,0,0,1,1,1,1,1]
ypred = [1,1,0,0,0,0,0,0,1,1]
cm = confusion_matrix(actual, ypred)

#             Predicted
#            0        1
# Actual 0   TN       FP
# Actual 1   FN       TP

# correctly classified = TN + TP
# wrongly predicted = FP + FN

 # 0 0 -------> true negative
 # 1 1 -------> true positive
 # 1 0 -------> false negative
 # 0 1 -------> false positive

 # find precision, negative predictive value, accuracy, Sensitivity, specificity

In [39]:
cm

array([[3, 2],
       [3, 2]])

In [40]:
TN, FP, FN, TP = cm.ravel()   # convert to 1D
accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
npv = TN / (TN + FN)
sensitivity = TP / (TP + FN)
specificity = TN / (TN + FP)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Negative Predictive Value:", npv)
print("Sensitivity:", sensitivity)
print("Specificity:", specificity)

Accuracy: 0.5
Precision: 0.5
Negative Predictive Value: 0.5
Sensitivity: 0.4
Specificity: 0.6

In [37]:
print(classification_report(actual,ypred))

              precision    recall  f1-score   support

           0       1.00      0.60      0.75         5
           1       0.71      1.00      0.83         5

    accuracy                           0.80        10
   macro avg       0.86      0.80      0.79        10
weighted avg       0.86      0.80      0.79        10

In [33]:
# sentivity - true things were predicted
# specificity - predict the mis-classified value
# accuracy - for overall

# Task - 2

In [53]:

f= open("file98.csv","w")
f.write("""x1,x2
-3,0
3,3
6,5
10,20
3,4
1,8
6,4
3,8
1,6""")
f.close()

In [54]:
df = pd.read_csv("file98.csv")
df

   x1  x2
0  -3   0
1   3   3
2   6   5
3  10  20
4   3   4
5   1   8
6   6   4
7   3   8
8   1   6

In [55]:
df["res"] = (-1*df["x1"])+(0*df["x2"])
df

   x1  x2  res
0  -3   0    3
1   3   3   -3
2   6   5   -6
3  10  20  -10
4   3   4   -3
5   1   8   -1
6   6   4   -6
7   3   8   -3
8   1   6   -1

In [56]:
df["value"] = df["res"].apply(lambda x: "positive" if x < 0 else "negative")
df

   x1  x2  res     value
0  -3   0    3  negative
1   3   3   -3  positive
2   6   5   -6  positive
3  10  20  -10  positive
4   3   4   -3  positive
5   1   8   -1  positive
6   6   4   -6  positive
7   3   8   -3  positive
8   1   6   -1  positive

# Super vector machine - svm

In [ ]:
# self learning ==============
# what is soft hyper plane
# slack variable
# log likehood
# roc and auc
# xgboost

In [58]:
f = open("file70.csv","w")
f.write("""outlook,temp,humidity,windy,play_goal
sunny,hot,high,false,no
sunny,hot,high,true,no
overcast,hot,high,false,yes
rainy,mild,high,false,yes
rainy,cool,normal,false,yes
rainy,cool,normal,true,no
overcast,cool,normal,true,yes
sunny,mild,high,false,no
sunny,cool,normal,false,yes
rainy,mild,normal,false,yes
sunny,mild,normal,true,yes
overcast,mild,high,true,yes
overcast,hot,normal,false,yes
rainy,mild,high,true,no
sunny,hot,normal,false,yes
""")
f.close()

In [59]:
df = pd.read_csv("file70.csv")
df

     outlook  temp humidity  windy play_goal
0      sunny   hot     high  False        no
1      sunny   hot     high   True        no
2   overcast   hot     high  False       yes
3      rainy  mild     high  False       yes
4      rainy  cool   normal  False       yes
5      rainy  cool   normal   True        no
6   overcast  cool   normal   True       yes
7      sunny  mild     high  False        no
8      sunny  cool   normal  False       yes
9      rainy  mild   normal  False       yes
10     sunny  mild   normal   True       yes
11  overcast  mild     high   True       yes
12  overcast   hot   normal  False       yes
13     rainy  mild     high   True        no
14     sunny   hot   normal  False       yes

In [60]:
from sklearn import tree

In [ ]:
df_default = decisiontreeclasssifer()