## Day 5

In [39]:
import pandas as pd
import numpy as np

In [70]:

f = open("file12.csv","w")
f.write("""x,y
1,1.2
2,1.8
3,2.6
4,3.2
5,3.8
""")
f.close()

In [71]:
df = pd.read_csv("file12.csv")
df

   x    y
0  1  1.2
1  2  1.8
2  3  2.6
3  4  3.2
4  5  3.8

In [72]:
df["xy"] = df["x"]*df["y"]
df

   x    y    xy
0  1  1.2   1.2
1  2  1.8   3.6
2  3  2.6   7.8
3  4  3.2  12.8
4  5  3.8  19.0

In [73]:
df["x^2"] = df["x"]**2
df

   x    y    xy  x^2
0  1  1.2   1.2    1
1  2  1.8   3.6    4
2  3  2.6   7.8    9
3  4  3.2  12.8   16
4  5  3.8  19.0   25

In [74]:
x_mean = (df["x"].sum())/len(df["x"])
x_mean

np.float64(3.0)

In [75]:
y_mean = (df["y"].sum())/len(df["y"])
y_mean

np.float64(2.5200000000000005)

In [76]:
x_sqr = (df["x^2"].sum())/len(df["x^2"])
x_sqr

np.float64(11.0)

In [77]:
xy = df["xy"].mean()
xy

np.float64(8.88)

In [80]:
t = x_mean**2
t

np.float64(9.0)

In [81]:
res = ((xy)-(x_mean*y_mean))/((x_sqr)-(t))
print(res)

0.6599999999999997

## Question 2

### Linear Regression Machine Learning Model

In [92]:
import numpy as np
from sklearn.linear_model import LinearRegression

model = LinearRegression()

x = np.array(df["x"]).reshape(-1,1)
y = np.array(df["y"])

model.fit(x, y) # training 


print("Intercept:", model.intercept_)
print("Coefficient:", model.coef_)

#predict model
model.predict([[7]])

Intercept: 0.5400000000000005
Coefficient: [0.66]

array([5.16])

# Question 3

In [19]:

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# create csv file
f = open("data56.csv","w")
f.write("""name	rain	water	dust	air	mud	yield
a	100	100	0	100	100	100
b	80	0	100	10	20	20
c	70	100	0	100	70	70
d	40	0	0	100	0	10
e	50	50	10	80	80	75
f	80	100	10	80	80	70
g	95	100	20	70	75	75
h	80	80	0	80	100	95
i	40	10	60	40	60	50
j	50	10	70	45	65	70
k	100	100	0	100	100	100
l	80	0	100	10	20	20
m	70	100	0	100	70	70
n	40	0	0	100	0	10
o	50	50	10	80	80	75
p	80	100	10	80	80	70
q	95	100	20	70	75	75
s	80	80	0	80	100	95
t	40	10	60	40	60	50
u	50	10	70	45	65	70
v	100	100	0	100	70	70
w	80	0	0	100	0	10
x	70	50	10	80	80	75
y	40	100	10	80	80	70
z	50	50	10	80	80	75
""")
f.close()

# read dataset
df = pd.read_csv("data56.csv", sep="\t")

# input features
X = df[["rain","water","dust","air","mud"]]

# output
y = df["yield"]

# model
model = LinearRegression()

# train
model.fit(X,y)

print("Intercept:     ", model.intercept_)
print("Coefficients:     ", model.coef_)

predict = model.predict([[90, 100, 10, 80, 85]])
print(predict)

Intercept:      -40.54289983622357
Coefficients:      [ 0.11251873 -0.07886885  0.28748579  0.43856497  0.94805575]
[80.24169558]

C:\Users\MEPZ\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(